# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
# on:
#   schedule:
#       # every 6 hours
#     - cron: "0 */6 * * *"

# # This command allows us to run the Action automatically from the Actions tab.
  # workflow_dispatch:

# Controls when the action will run. This action only runs manually.
# on:
#   workflow_dispatch:


# Controls when the action will run
on:
  # Runs the action daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allows manual triggering
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Randomize the execution, run only once in 7 days for scheduled events
      - name: Random execution once in 7 days (for scheduled runs)
        if: github.event_name == 'schedule' # Skip this step for manual runs
        run: |
          RANDOM_DAY=$(( ( RANDOM % 7 ) + 1 ))
          TODAY=$(date +%u) # Get the day of the week (1-7)
          if [[ "$TODAY" -ne "$RANDOM_DAY" ]]; then
            echo "Skipping execution for today. Random day: $RANDOM_DAY, Today: $TODAY"
            exit 0
          fi
        shell: bash
        
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

      # Generates the snake  
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/only-svg/github-contribution-grid-snake.svg
            dist/only-svg/github-contribution-grid-snake-dark.svg?palette=github-dark

      # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/svg-and-gif/github-contribution-grid-snake.svg
            dist/svg-and-gif/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/svg-and-gif/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9


      # Push the changes
      - name: Commit and push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Ensure this branch is not protected
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
